[project]
name = "calc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio>=3.4.3",
]

[tool.basedpyright]
typeCheckingMode = "basic"

[tool.ty.environment]
python = "./.venv"
